#!/bin/sh


SPROCKET_APP_NAME=analytics-engine
SPROCKET_PACKAGE_DIR=package
SPROCKET_DEST_DIR=/data/$SPROCKET_APP_NAME

SPROCKET_UPSTART=upstart.conf
SPROCKET_MONIT=monit.conf
SPROCKET_CLOUD_USER=sparcloud-boss
SPROCKET_CLOUD_GROUP=sparcloud
